name: nilediting_app
description: "Nil Editing Web App"
publish_to: "Play Store"
version: 1.0.2+4

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0

  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
